### Zadanie: kupujemy mieszkanie
Zamierzasz kupić mieszkanie. Upatrzone M kosztuje w tym momencie 120 tys. zł, jednak przewidujesz, że przez następne 5 lat ceny mieszkań będą rosły w tempie 5% rocznie. W tym momencie nie dysponujesz wystarczającymi środkami, dlatego znajdujesz ofertę banku, który proponuje lokatę, do której dopłacasz pewna stałą kwotę na koniec każdego miesiąca. Bank oferuje nominalną stopę procentową w wysokości 12% w skali roku, przy kapitalizacji miesięcznej.

1. Ile będzie wynosiła orientacyjna cena mieszkania za 5 lat?
2. Ile musisz wpłacać do banku każdego miesiąca, aby przy przedstawionej ofercie uzbierać na mieszkanie w ciągu 5 lat?
3. Stwórz wykres przedstawiający, jak w interwałach miesięcznych zmieniać się będzie cena mieszkania (liniowy wzrost w całym okresie) oraz wartość twojej lokaty.

Do wykonania powyższego zadania wykorzystaj biblioteki NumPy, NumPy-financial oraz Matplotlib. Odpowiedzi na pytania umieść w Notebooku (jeśli korzystasz) lub w komentarzach w kodzie.

In [1]:
# Dane wstępne
import numpy as np

current_price = 120000
years = 5
price_rate = 0.05
rate = 0.12
freq = 12

for i in range(years):
    current_price = current_price*(1 + price_rate)

np.round(current_price, 2)
# Poniżej cena mieszkania za pięć lat przy założeniu 5-procentowego wzrostu cen mieszkań każdego roku
# Czyli jest to odpowiedź na 1. pytanie zadania: "Ile będzie wynosiła orientacyjna cena mieszkania za 5 lat?"

153153.79

In [2]:
# stopa oprocentowania lokaty w ujęciu miesięcznym
rate = rate / freq
rate

0.01

In [3]:
nper = years * freq
periods = np.arange(1,nper+1,dtype=int)
periods

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [4]:
nper
# liczba miesięcznych okresów kapitalizacji odsetek

60

In [7]:
# Poniżej obliczenia dotyczące 2. punktu zadania:
# Ile musisz wpłacać do banku każdego miesiąca, aby przy przedstawionej ofercie uzbierać na mieszkanie w ciągu 5 lat?

# Poniżej liczymy mnożnik dla każdej wpłaconej raty, czyli dowiemy się stąd, o ile więcej pieniędzy przyniesie nam każda wpłata do banku, przy każdomiesięcznej kapitalizacji odsetek. Na pierwszej pozycji mamy ostatnią wpłaconą ratę, czyli wpłaconą w 59-tym miesiącu - ona zdąży nam wypracować tylko 1.01, czyli tylko 1% zysku. Na ostatniej pozycji mamy pierwszą wpłaconą ratę, czyli tą która rozpoczęłą całe oszczędzanie na mieszkanie. Ona wypracuje zysk przez 60 miesięcy, czyli (1.01) do potęgi 60, co daje prawie, 1.82, czyli wypracuje nam 82% zysku.

"""
W obliczeniach skorzystano ze wzoru na obliczenie wartości przyszłej:
FV = PV(1 + i)t
FV - wartość przyszła
PV - wartość obecna
i - oprocentowanie w okresie kapitalizacji
t - czas wyrażony w okresach kapitalizacji
(1 + i) jest podnoszone do potęgi t
"""
multiplier = np.zeros(nper) + (1 + rate)**periods
multiplier

array([1.01      , 1.0201    , 1.030301  , 1.04060401, 1.05101005,
       1.06152015, 1.07213535, 1.08285671, 1.09368527, 1.10462213,
       1.11566835, 1.12682503, 1.13809328, 1.14947421, 1.16096896,
       1.17257864, 1.18430443, 1.19614748, 1.20810895, 1.22019004,
       1.23239194, 1.24471586, 1.25716302, 1.26973465, 1.282432  ,
       1.29525631, 1.30820888, 1.32129097, 1.33450388, 1.34784892,
       1.3613274 , 1.37494068, 1.38869009, 1.40257699, 1.41660276,
       1.43076878, 1.44507647, 1.45952724, 1.47412251, 1.48886373,
       1.50375237, 1.51878989, 1.53397779, 1.54931757, 1.56481075,
       1.58045885, 1.59626344, 1.61222608, 1.62834834, 1.64463182,
       1.66107814, 1.67768892, 1.69446581, 1.71141047, 1.72852457,
       1.74580982, 1.76326792, 1.7809006 , 1.7987096 , 1.8166967 ])

In [8]:
# Jeśli obliczymy teraz skumulowane wartości to na ostatniej pozycji wektora otrzymamy wartość mnożnika dla wszystkich wpłaconych 60 rat przez okres 5 lat.

multiplier_cumulative = np.cumsum(multiplier)
multiplier_cumulative

array([ 1.01      ,  2.0301    ,  3.060401  ,  4.10100501,  5.15201506,
        6.21353521,  7.28567056,  8.36852727,  9.46221254, 10.56683467,
       11.68250301, 12.80932804, 13.94742132, 15.09689554, 16.25786449,
       17.43044314, 18.61474757, 19.81089504, 21.01900399, 22.23919403,
       23.47158598, 24.71630183, 25.97346485, 27.2431995 , 28.5256315 ,
       29.82088781, 31.12909669, 32.45038766, 33.78489153, 35.13274045,
       36.49406785, 37.86900853, 39.25769862, 40.6602756 , 42.07687836,
       43.50764714, 44.95272361, 46.41225085, 47.88637336, 49.37523709,
       50.87898946, 52.39777936, 53.93175715, 55.48107472, 57.04588547,
       58.62634432, 60.22260777, 61.83483385, 63.46318218, 65.10781401,
       66.76889215, 68.44658107, 70.14104688, 71.85245735, 73.58098192,
       75.32679174, 77.09005966, 78.87096025, 80.66966986, 82.48636655])

In [10]:
# Teraz aby dowiedzieć się, ile wynosi rata wpłacana każdego miesiąca na konto oszczędnościowe, aby uzbierać na wymarzone mieszkanie, wystarczy przyszłą wartość mieszkania (za 5 lat) podzielić przez ostatnią wartość z wektora obliczonych skumulowanych mnożników.

payment = np.around(current_price / multiplier_cumulative[-1], 2)
payment

1856.72