In [4]:
freq = 12
rate = 0.12
years = 5
monthly = 2000

rate /= freq
rate 

0.01

In [5]:
nper = years * freq 
nper

60

In [7]:
import numpy as np
periods = np.arange(1,nper+1,dtype=int)
periods

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [26]:
wplacane_co_miesiac = np.around(np.zeros(nper) + monthly, 2)
wplacane_co_miesiac

array([2000., 2000., 2000., 2000., 2000., 2000., 2000., 2000., 2000.,
       2000., 2000., 2000., 2000., 2000., 2000., 2000., 2000., 2000.,
       2000., 2000., 2000., 2000., 2000., 2000., 2000., 2000., 2000.,
       2000., 2000., 2000., 2000., 2000., 2000., 2000., 2000., 2000.,
       2000., 2000., 2000., 2000., 2000., 2000., 2000., 2000., 2000.,
       2000., 2000., 2000., 2000., 2000., 2000., 2000., 2000., 2000.,
       2000., 2000., 2000., 2000., 2000., 2000.])

In [9]:
wplacony_kapital = np.zeros(nper) + np.cumsum(wplacane_co_miesiac)
wplacony_kapital

array([  2000.,   4000.,   6000.,   8000.,  10000.,  12000.,  14000.,
        16000.,  18000.,  20000.,  22000.,  24000.,  26000.,  28000.,
        30000.,  32000.,  34000.,  36000.,  38000.,  40000.,  42000.,
        44000.,  46000.,  48000.,  50000.,  52000.,  54000.,  56000.,
        58000.,  60000.,  62000.,  64000.,  66000.,  68000.,  70000.,
        72000.,  74000.,  76000.,  78000.,  80000.,  82000.,  84000.,
        86000.,  88000.,  90000.,  92000.,  94000.,  96000.,  98000.,
       100000., 102000., 104000., 106000., 108000., 110000., 112000.,
       114000., 116000., 118000., 120000.])

In [27]:
odsetki_od_kapitalu = np.zeros(nper) + wplacony_kapital*rate
odsetki_od_kapitalu

array([  20.,   40.,   60.,   80.,  100.,  120.,  140.,  160.,  180.,
        200.,  220.,  240.,  260.,  280.,  300.,  320.,  340.,  360.,
        380.,  400.,  420.,  440.,  460.,  480.,  500.,  520.,  540.,
        560.,  580.,  600.,  620.,  640.,  660.,  680.,  700.,  720.,
        740.,  760.,  780.,  800.,  820.,  840.,  860.,  880.,  900.,
        920.,  940.,  960.,  980., 1000., 1020., 1040., 1060., 1080.,
       1100., 1120., 1140., 1160., 1180., 1200.])

In [28]:
odsetki_od_kapitalu_kum = np.cumsum(odsetki_od_kapitalu)
odsetki_od_kapitalu_kum

array([2.000e+01, 6.000e+01, 1.200e+02, 2.000e+02, 3.000e+02, 4.200e+02,
       5.600e+02, 7.200e+02, 9.000e+02, 1.100e+03, 1.320e+03, 1.560e+03,
       1.820e+03, 2.100e+03, 2.400e+03, 2.720e+03, 3.060e+03, 3.420e+03,
       3.800e+03, 4.200e+03, 4.620e+03, 5.060e+03, 5.520e+03, 6.000e+03,
       6.500e+03, 7.020e+03, 7.560e+03, 8.120e+03, 8.700e+03, 9.300e+03,
       9.920e+03, 1.056e+04, 1.122e+04, 1.190e+04, 1.260e+04, 1.332e+04,
       1.406e+04, 1.482e+04, 1.560e+04, 1.640e+04, 1.722e+04, 1.806e+04,
       1.892e+04, 1.980e+04, 2.070e+04, 2.162e+04, 2.256e+04, 2.352e+04,
       2.450e+04, 2.550e+04, 2.652e+04, 2.756e+04, 2.862e+04, 2.970e+04,
       3.080e+04, 3.192e+04, 3.306e+04, 3.422e+04, 3.540e+04, 3.660e+04])

In [30]:
odsetki_od_odsetek = odsetki_od_kapitalu_kum*rate
odsetki_od_odsetek

array([2.000e-01, 6.000e-01, 1.200e+00, 2.000e+00, 3.000e+00, 4.200e+00,
       5.600e+00, 7.200e+00, 9.000e+00, 1.100e+01, 1.320e+01, 1.560e+01,
       1.820e+01, 2.100e+01, 2.400e+01, 2.720e+01, 3.060e+01, 3.420e+01,
       3.800e+01, 4.200e+01, 4.620e+01, 5.060e+01, 5.520e+01, 6.000e+01,
       6.500e+01, 7.020e+01, 7.560e+01, 8.120e+01, 8.700e+01, 9.300e+01,
       9.920e+01, 1.056e+02, 1.122e+02, 1.190e+02, 1.260e+02, 1.332e+02,
       1.406e+02, 1.482e+02, 1.560e+02, 1.640e+02, 1.722e+02, 1.806e+02,
       1.892e+02, 1.980e+02, 2.070e+02, 2.162e+02, 2.256e+02, 2.352e+02,
       2.450e+02, 2.550e+02, 2.652e+02, 2.756e+02, 2.862e+02, 2.970e+02,
       3.080e+02, 3.192e+02, 3.306e+02, 3.422e+02, 3.540e+02, 3.660e+02])

In [31]:
odsetki_od_odsetek_kum = np.cumsum(odsetki_od_odsetek)
odsetki_od_odsetek_kum

array([2.0000e-01, 8.0000e-01, 2.0000e+00, 4.0000e+00, 7.0000e+00,
       1.1200e+01, 1.6800e+01, 2.4000e+01, 3.3000e+01, 4.4000e+01,
       5.7200e+01, 7.2800e+01, 9.1000e+01, 1.1200e+02, 1.3600e+02,
       1.6320e+02, 1.9380e+02, 2.2800e+02, 2.6600e+02, 3.0800e+02,
       3.5420e+02, 4.0480e+02, 4.6000e+02, 5.2000e+02, 5.8500e+02,
       6.5520e+02, 7.3080e+02, 8.1200e+02, 8.9900e+02, 9.9200e+02,
       1.0912e+03, 1.1968e+03, 1.3090e+03, 1.4280e+03, 1.5540e+03,
       1.6872e+03, 1.8278e+03, 1.9760e+03, 2.1320e+03, 2.2960e+03,
       2.4682e+03, 2.6488e+03, 2.8380e+03, 3.0360e+03, 3.2430e+03,
       3.4592e+03, 3.6848e+03, 3.9200e+03, 4.1650e+03, 4.4200e+03,
       4.6852e+03, 4.9608e+03, 5.2470e+03, 5.5440e+03, 5.8520e+03,
       6.1712e+03, 6.5018e+03, 6.8440e+03, 7.1980e+03, 7.5640e+03])

In [32]:
oszczednosci = wplacony_kapital + odsetki_od_kapitalu_kum + odsetki_od_odsetek_kum
oszczednosci

array([  2020.2,   4060.8,   6122. ,   8204. ,  10307. ,  12431.2,
        14576.8,  16744. ,  18933. ,  21144. ,  23377.2,  25632.8,
        27911. ,  30212. ,  32536. ,  34883.2,  37253.8,  39648. ,
        42066. ,  44508. ,  46974.2,  49464.8,  51980. ,  54520. ,
        57085. ,  59675.2,  62290.8,  64932. ,  67599. ,  70292. ,
        73011.2,  75756.8,  78529. ,  81328. ,  84154. ,  87007.2,
        89887.8,  92796. ,  95732. ,  98696. , 101688.2, 104708.8,
       107758. , 110836. , 113943. , 117079.2, 120244.8, 123440. ,
       126665. , 129920. , 133205.2, 136520.8, 139867. , 143244. ,
       146652. , 150091.2, 153561.8, 157064. , 160598. , 164164. ])

In [8]:
import numpy as np
x = np.zeros(nper) + (1.01)**periods
x

array([1.01      , 1.0201    , 1.030301  , 1.04060401, 1.05101005,
       1.06152015, 1.07213535, 1.08285671, 1.09368527, 1.10462213,
       1.11566835, 1.12682503, 1.13809328, 1.14947421, 1.16096896,
       1.17257864, 1.18430443, 1.19614748, 1.20810895, 1.22019004,
       1.23239194, 1.24471586, 1.25716302, 1.26973465, 1.282432  ,
       1.29525631, 1.30820888, 1.32129097, 1.33450388, 1.34784892,
       1.3613274 , 1.37494068, 1.38869009, 1.40257699, 1.41660276,
       1.43076878, 1.44507647, 1.45952724, 1.47412251, 1.48886373,
       1.50375237, 1.51878989, 1.53397779, 1.54931757, 1.56481075,
       1.58045885, 1.59626344, 1.61222608, 1.62834834, 1.64463182,
       1.66107814, 1.67768892, 1.69446581, 1.71141047, 1.72852457,
       1.74580982, 1.76326792, 1.7809006 , 1.7987096 , 1.8166967 ])

In [10]:
y = np.cumsum(x)
y

array([ 1.01      ,  2.0301    ,  3.060401  ,  4.10100501,  5.15201506,
        6.21353521,  7.28567056,  8.36852727,  9.46221254, 10.56683467,
       11.68250301, 12.80932804, 13.94742132, 15.09689554, 16.25786449,
       17.43044314, 18.61474757, 19.81089504, 21.01900399, 22.23919403,
       23.47158598, 24.71630183, 25.97346485, 27.2431995 , 28.5256315 ,
       29.82088781, 31.12909669, 32.45038766, 33.78489153, 35.13274045,
       36.49406785, 37.86900853, 39.25769862, 40.6602756 , 42.07687836,
       43.50764714, 44.95272361, 46.41225085, 47.88637336, 49.37523709,
       50.87898946, 52.39777936, 53.93175715, 55.48107472, 57.04588547,
       58.62634432, 60.22260777, 61.83483385, 63.46318218, 65.10781401,
       66.76889215, 68.44658107, 70.14104688, 71.85245735, 73.58098192,
       75.32679174, 77.09005966, 78.87096025, 80.66966986, 82.48636655])

In [4]:
import numpy as np
current_price = 120000
years = 5
price_rate = 0.05

current_price = current_price*(1 + price_rate)**years
np.round(current_price, -2)

153200.0